== N2DE (Nyquist 2D Engine)
=== Directories
----
.
├── config.mk <---- Global compiling configuration
├── docs
│   └── notes.adoc
├── <game name> <--------------------│ Editable lua files for bulk of game logic
│   ├── init.lua <----------------│ Entry point for game scripting
│   └── libs <-----------------| C libraries are added here. The library
│         │                    │ Classes can be modified
│         └── stdlibs
│            ├── init.lua <----│ Init for basic standard lua c libraries for 
│            │                 │ engine.
│            └── lib.so
├── LICENSE
├── linux.mk <------│ Compiling configuration for linux
├── Makefile
├── README.adoc
├── src
│   ├── n2de <---------------------│ Engine written in C here
│   │   ├── n2de <----│ Entry point for game engine
│   │   ├── n2de.h <----│
│   │   ├── error.c <---│ Logging errors
│   │   └── error.h <---│ 
│   ├── global.h
│   └── lua-libraries <--------------------│ Write C libraries for lua here
│       ├── stdlib.c <----│ Basic c Libraries for lua
│       └── stdlib.h <----│
└── windows.mk <-----│ Compiling configuration for windows
----

== Compiling

You must compile in linux. The game will be able to run in linux and windows.
WSL is perfectly exceptable to compile in. Make sure to edit the paths of the
`LIBS` variable in _windows.mk_ and the includes of_src/config.h_ to the
appropriate values. To change other game related variables like the name of the
game check _config.mk_. The Required DLL files need to game in the root folder
for the game directory.

=== Building engine

Windows

----
make
----

Linux

----
make LINUX=true
----

=== Building libs

Windows

----
make lib LIB=<lib name>
----

Linux

----
sudo make lib LINUX=true LIB=<lib name>
----

WARNING: sudo is import so you can set file permision correctly

NOTE: You must build the engine and the stdlib lib for the game to run!

== Running

Linux

----
cd <name of game>
./<name of game>
----

Windows

----
cd <name of game>
./<name of game>.exe
----

=== Dependencies
- Mingw - x86_64-w64-mingw32-gcc
- gcc
- SDL2.lib
- SDL2.dll
- lua5.4.exe
- lua5.4.lib
- lua5.4.dll
- libsdl2-dev
- liblua5.4-dev
- libgl1-mesa-glx (libGL.so)

== Todo
- [ ] Use https://doxygen.nl/index.html[doxygen] for documentation
- [ ] Create github wiki page for more detailed information
- [ ] Switch to SDL3
- [ ] Use GTK for gui elements of engine (not game)
